# Generated by Django 3.1.7 on 2021-05-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0007_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='credit',
            new_name='Lyric',
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
