# Generated by Django 3.1.7 on 2021-05-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0008_auto_20210507_2116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.AlterField(
            model_name='song',
            name='Lyric',
            field=models.TextField(),
        ),
    ]
